In [34]:
!pip install pymysql
import pymysql

host='49.247.130.147'
username='root'
password='jihyun0127'
db_name='kpc_test'
db= pymysql.connect(host=host, user=username, passwd=password, db=db_name, connect_timeout=1)

Requirement already satisfied: pymysql in /usr/local/lib/python3.6/dist-packages (0.9.3)

In [0]:
from sqlalchemy import create_engine

host='49.247.130.147'
username='root'
password='jihyun0127'
db_name='kpc_test'
engine = create_engine("mysql+pymysql://"+username+":"+password+"@"+host+":3306/"+db_name+"?charset=utf8", encoding='utf-8')
conn = engine.connect()

In [0]:
curs = db.cursor()
sql = "ALTER TABLE kpc_test.att_table DROP image"
curs.execute(sql)
result = curs.fetchall()

KeyboardInterrupt: ignored

In [37]:
import pandas as pd
from google.colab import drive
drive.mount('/gdrive',force_remount=True)

data = pd.read_csv("/gdrive/My Drive/review_table_1.csv",encoding='utf-8')

Mounted at /gdrive

In [39]:
data

       ind       id           user  ...  keyword1 keyword2 keyword3
0        1  1169465  Cyril Grace R  ...       NaN      NaN      NaN
1        2   553546  Cyril Grace R  ...       NaN      NaN      NaN
2        3   324888  Cyril Grace R  ...       NaN      NaN      NaN
3        4  1169465        Blossom  ...       NaN      NaN      NaN
4        5  1169465           Kens  ...       NaN      NaN      NaN
...    ...      ...            ...  ...       ...      ...      ...
4446  4447  3957040       Debbie L  ...       NaN      NaN      NaN
4447  4448  3957040     Momof3inIA  ...       NaN      NaN      NaN
4448  4449  3957040        Alisa B  ...       NaN      NaN      NaN
4449  4450  3957040        Perry F  ...       NaN      NaN      NaN
4450  4451  3957040       Jyang017  ...       NaN      NaN      NaN

[4451 rows x 9 columns]

In [0]:
del data['seq']

In [43]:
data.to_sql(name='review_table', con=engine, if_exists='append',index=False)

InternalError: ignored

In [0]:
result[0][1]

'창덕궁'

In [26]:
import pandas as pd

df = pd.read_sql('SELECT * FROM kpc_test.type_table', con=conn)
df.head()

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive

ProgrammingError: ignored

In [0]:
df.to_csv('type_table.csv',index=False)
from google.colab import drive
drive.mount('/gdrive',force_remount=True)
df.to_csv('/gdrive/My Drive/type_table.csv',index=False)
!ls /gdrive/My\ Drive/

Mounted at /gdrive
 포트폴리오		'Colab Notebooks'		  review_table_1.csv
 att_table_1.csv	 da				  review_table.csv
 att_table_2.csv	'data for R'			  type_table_1.csv
 att_table.csv		 data_share			  type_table.csv
 att_table.gsheet	 final_att_table_seoul_1.csv	  user_table.csv
 att_table_seoul_1.csv	 final_review_table_seoul_1.csv

In [0]:

df.loc[df['type'] == 'T010201', 'type'] = 'T010203'

In [0]:
df[df['type'] == 'T010302']

         id  name  star  ...     loid location image
98  6847826  두물머리    45  ...  1138011        1  None

[1 rows x 12 columns]

In [0]:
df.to_csv('att_table_2.csv',index=False)
from google.colab import drive
drive.mount('/gdrive',force_remount=True)
df.to_csv('/gdrive/My Drive/att_table_2.csv',index=False)
!ls /gdrive/My\ Drive/

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
 포트폴리오		'Colab Notebooks'		  review_table_1.csv
 att_table_1.csv	 da				  review_table.csv
 att_table_2.csv	'data for R'			  type_table_1.csv
 att_table.csv		 data_share			  type_table.csv
 att_table.gsheet	 final_att_table_seoul_1.csv	  user_table.csv
 att_table_seoul_1.csv	 final_review_table_seoul_1.csv

In [0]:
df.columns = ['seq','user','age','sex','addr','PW','email']

In [0]:
df

       seq           user   age   sex  addr    PW email
0        0  Cyril Grace R  None  None  None  None  None
1        1        Blossom  None  None  None  None  None
2        2           Kens  None  None  None  None  None
3        3    Catherine Q  None  None  None  None  None
4        4       jrrjr619  None  None  None  None  None
...    ...            ...   ...   ...   ...   ...   ...
2968  2968       Debbie L  None  None  None  None  None
2969  2969     Momof3inIA  None  None  None  None  None
2970  2970        Alisa B  None  None  None  None  None
2971  2971        Perry F  None  None  None  None  None
2972  2972       Jyang017  None  None  None  None  None

[2973 rows x 7 columns]

In [0]:
m.to_sql(name='review_table_1', con=engine, if_exists='append',index=False)

InternalError: ignored

In [0]:
from google.colab import drive
drive.mount('/gdrive',force_remount=True)
rev = pd.read_csv("/gdrive/My Drive/review_table_1.csv",encoding='utf-8')

Mounted at /gdrive

In [0]:
rev

           id  ...                                             review
0     1169465  ...  this place had 360 degree vies of seoul.best t...
1     1169465  ...  The Korean Drama that left the biggest impact ...
2     1169465  ...  I went to Namsan on my first day at Seoul. I w...
3     1169465  ...  If your in Seoul you should visit the N Tower....
4     1169465  ...  The N Seoul Tower is relatively easy to get to...
...       ...  ...                                                ...
4586  3957040  ...  We enjoyed this museum & the interactive aspec...
4587  3957040  ...  Museum provides the history of korea from the ...
4588  3957040  ...  If you are into modern art, just go there and ...
4589  3957040  ...  This is a fantastic museum to get a better und...
4590  3957040  ...  I did not expect any Korean museum to be even ...

[4591 rows x 5 columns]

In [0]:
m=pd.merge(rev,df,on='user')

In [0]:
del m['age']
del m['sex']
del m['addr']
del m['PW']
del m['email']

In [0]:
m.columns = ['id','user','star','month','reveiw','seq']

In [0]:
m.to_csv('review_table_1.csv',index=False)

m.to_csv('/gdrive/My Drive/review_table_1.csv',index=False)
!ls /gdrive/My\ Drive/

 포트폴리오		'data for R'			  review_table.csv
 att_table.csv		 data_share			  type_table.csv
 att_table_seoul_1.csv	 final_att_table_seoul_1.csv	  user_table.csv
'Colab Notebooks'	 final_review_table_seoul_1.csv
 da			 review_table_1.csv

In [0]:
dd = pd.merge(rev, df, on = 'user')

In [0]:
rev['index'] = dd['index_y']

In [0]:
m.to_csv('review_table_1.csv',index=False)
m.to_csv('/gdrive/My Drive/review_table_1.csv',index=False)
!ls /gdrive/My\ Drive/

 포트폴리오		'data for R'			  review_table.csv
 att_table.csv		 data_share			  type_table.csv
 att_table_seoul_1.csv	 final_att_table_seoul_1.csv	  user_table.csv
'Colab Notebooks'	 final_review_table_seoul_1.csv
 da			 review_table_1.csv

In [0]:
from google.colab import drive
drive.mount('/gdrive',force_remount=True)
!ls "/gdrive/My Drive"
import numpy as np
import pandas as pd

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
 포트폴리오		 data_share
 att_table.csv		 final_att_table_seoul_1.csv
 att_table_seoul_1.csv	 final_review_table_seoul_1.csv
'Colab Notebooks'	 review_table.csv
 da			 type_table.csv
'data for R'		 user_table.csv

In [0]:
movies

               user  age  sex  addr  PW  email
0     Cyril Grace R  NaN  NaN   NaN NaN    NaN
1           Blossom  NaN  NaN   NaN NaN    NaN
2              Kens  NaN  NaN   NaN NaN    NaN
3       Catherine Q  NaN  NaN   NaN NaN    NaN
4          jrrjr619  NaN  NaN   NaN NaN    NaN
...             ...  ...  ...   ...  ..    ...
2968       Debbie L  NaN  NaN   NaN NaN    NaN
2969     Momof3inIA  NaN  NaN   NaN NaN    NaN
2970        Alisa B  NaN  NaN   NaN NaN    NaN
2971        Perry F  NaN  NaN   NaN NaN    NaN
2972       Jyang017  NaN  NaN   NaN NaN    NaN

[2973 rows x 6 columns]

In [0]:
movies.drop_duplicates()

               user  age  sex  addr  PW  email
0     Cyril Grace R  NaN  NaN   NaN NaN    NaN
1           Blossom  NaN  NaN   NaN NaN    NaN
2              Kens  NaN  NaN   NaN NaN    NaN
3       Catherine Q  NaN  NaN   NaN NaN    NaN
4          jrrjr619  NaN  NaN   NaN NaN    NaN
...             ...  ...  ...   ...  ..    ...
2968       Debbie L  NaN  NaN   NaN NaN    NaN
2969     Momof3inIA  NaN  NaN   NaN NaN    NaN
2970        Alisa B  NaN  NaN   NaN NaN    NaN
2971        Perry F  NaN  NaN   NaN NaN    NaN
2972       Jyang017  NaN  NaN   NaN NaN    NaN

[2973 rows x 6 columns]

In [0]:
movies.to_sql(name='new_table', con=engine, if_exists='append',index=True)

In [0]:
len(data)

84

In [0]:
movies.to_sql(name='att_table', con=engine, if_exists='append', index=False)